[language-server.gpt]
command = "helix-gpt"

[language-server.nil]
command = "nil"

[[language]]
name = "nix"
language-servers = [ "nil" ]

[[language]]
name = "rust"
language-servers = [
  "rust-analyzer",
  "gpt"
]
